import crypto from 'crypto';
import validateEnv from '../config/env';

const env = validateEnv();

const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH = 12; // 12 bytes for AES-GCM
const AUTH_TAG_LENGTH = 16;

/**
 * Encrypts plain text using AES-256-GCM.
 * Output format: iv_hex:auth_tag_hex:ciphertext_hex
 */
export function encryptText(text: string): string {
  if (!text) return '';
  try {
    const key = crypto.createHash('sha256').update(env.ENCRYPTION_KEY).digest();
    const iv = crypto.randomBytes(IV_LENGTH);
    const cipher = crypto.createCipheriv(ALGORITHM, key, iv);

    let encrypted = cipher.update(text, 'utf8', 'hex');
    encrypted += cipher.final('hex');
    const authTag = cipher.getAuthTag().toString('hex');

    return `${iv.toString('hex')}:${authTag}:${encrypted}`;
  } catch (error) {
    console.error('[Encryption] Failed to encrypt data:', error);
    return text; // Fallback to raw if encryption fails
  }
}

/**
 * Decrypts text generated by encryptText.
 * If text is not encrypted (does not match format), returns text as-is.
 */
export function decryptText(encryptedText: string): string {
  if (!encryptedText) return '';
  
  // Check format: iv:authTag:ciphertext
  const parts = encryptedText.split(':');
  if (parts.length !== 3) {
    return encryptedText; // Legacy unencrypted text
  }

  try {
    const key = crypto.createHash('sha256').update(env.ENCRYPTION_KEY).digest();
    const [ivHex, authTagHex, ciphertextHex] = parts;

    const iv = Buffer.from(ivHex, 'hex');
    const authTag = Buffer.from(authTagHex, 'hex');
    const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);

    decipher.setAuthTag(authTag);

    let decrypted = decipher.update(ciphertextHex, 'hex', 'utf8');
    decrypted += decipher.final('utf8');

    return decrypted;
  } catch (error) {
    // If decryption fails (e.g. invalid tag or raw string), return as is or error
    return encryptedText;
  }
}

/**
 * Masks a credit card number to show only the last 4 digits (e.g. **** **** **** 1234)
 */
export function maskCardNumber(cardNumber: string): string {
  if (!cardNumber) return '';
  const digits = cardNumber.replace(/\D/g, '');
  if (digits.length < 4) return '****';
  const last4 = digits.slice(-4);
  return `**** **** **** ${last4}`;
}
